In [72]:
import numpy as np

# Q6

In [80]:
M = np.array(
    [
        [0,0,0,0.2,0],
        [0,0,0,0.2,0],
        [0,0,0,0.2,0],
        [0,0.5,0.5,0.2,1],
        [1,0.5,0.5,0.2,0]
    ]
)
M

array([[0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0.5, 0.5, 0.2, 1. ],
       [1. , 0.5, 0.5, 0.2, 0. ]])

In [81]:
C = np.array(
    [
        [0.2,0.2,0.2,0.2,0.2],
        [0.2,0.2,0.2,0.2,0.2],
        [0.2,0.2,0.2,0.2,0.2],
        [0.2,0.2,0.2,0.2,0.2],
        [0.2,0.2,0.2,0.2,0.2]
    ]
)
C

array([[0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])

In [82]:
A = 0.8 * M + 0.2 * C
A

array([[0.04, 0.04, 0.04, 0.2 , 0.04],
       [0.04, 0.04, 0.04, 0.2 , 0.04],
       [0.04, 0.04, 0.04, 0.2 , 0.04],
       [0.04, 0.44, 0.44, 0.2 , 0.84],
       [0.84, 0.44, 0.44, 0.2 , 0.04]])

In [83]:
r0 = np.array([0.2,0.2,0.2,0.2,0.2])
r1 = np.dot(A, r0)
r2 = np.dot(A, r1)
r3 = np.dot(A, r2)

In [84]:
r1

array([0.072, 0.072, 0.072, 0.392, 0.392])

In [85]:
r2

array([0.10272, 0.10272, 0.10272, 0.47392, 0.21792])

In [86]:
r3

array([0.1158272, 0.1158272, 0.1158272, 0.3723392, 0.2801792])

# Q7

In [97]:
A = np.array([1,5,7,2,4])
A - A.mean()

array([-2.8,  1.2,  3.2, -1.8,  0.2])

In [98]:
B = np.array([4,3,3,5])
B - B.mean()

array([ 0.25, -0.75, -0.75,  1.25])

In [99]:
C = np.array([5,1,3,9])
C - C.mean()

array([ 0.5, -3.5, -1.5,  4.5])

In [100]:
D = np.array([6,9,8])
D - D.mean()

array([-1.66666667,  1.33333333,  0.33333333])

In [102]:
E = np.array([8,8,2,1])
E - E.mean()

array([ 3.25,  3.25, -2.75, -3.75])

In [104]:
from scipy.stats import pearsonr
x = np.array([-3.5, -0.5, 3.5])
y = np.array([-0.5, -2.5, 2.5])
pearsonr(x, y)

(0.6600250006041248, 0.5410913388046926)

In [109]:
x = np.array([-0.5, -2.5, 2.5])
y = np.array([3.75, -0.25, -1.25])
pearsonr(x, y)

(-0.3003757045930553, 0.8057758866359961)

In [110]:
x = np.array([-0.5, 0.5, 2.5])
y = np.array([-1.75, 5.25, -2.75])
pearsonr(x, y)

(-0.30037570459305524, 0.8057758866359961)

In [111]:
x = np.array([-0.5, -2.5, 2.5])
y = np.array([-2.5, -1.5, 1.5])
pearsonr(x, y)

(0.7953559537197222, 0.41456789660427257)

In [112]:
def sim(x, y):
    u = 0
    for i in x:
        for j in y:
            u += i * j
    b1 = 0
    b2 = 0
    for i in x:
        b1 += i**2
    for j in y:
        b2 += j**2
    
    return u / (b1**0.5 * b2**0.5)

In [113]:
sim([-2.8, 3.2, -1.8, 0.2], [0.5, -3.5, -1.5, 4.5])

-1.339952870269215e-16

# Q3

In [ ]:
for i in range()